theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
cursorline = true
color-modes = true
rulers = [80]
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
