theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
cursorline = true
color-modes = true
rulers = [80]
bufferline = "multiple"

[editor.lsp]
display-messages = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
